/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.io.*;

/**
 *
 * @author Antonio
 */
public class AlineacionAlAzar extends javax.swing.JFrame {

        Equipo equipo = new Equipo();

        /**
         * Creates new form AlineacionAlAzar
         */
        public AlineacionAlAzar() throws FileNotFoundException, IOException {
                initComponents();
                FileReader equipos = new FileReader("teams.dir");
                BufferedReader bR = new BufferedReader(equipos);
                String s;
                while ((s = bR.readLine()) != null) {
                        jEquipos.addItem(s);
                }
        }

        /**
         * This method is called from within the constructor to
         * initialize the form. WARNING: Do NOT modify this code. The
         * content of this method is always regenerated by the Form
         * Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jEquipos = new javax.swing.JComboBox<>();
        jAlineacionAlAzar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEquiposActionPerformed(evt);
            }
        });
        jPanel1.add(jEquipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 130, -1));

        jAlineacionAlAzar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jAlineacionAlAzar.setText("Crear Alineacion");
        jAlineacionAlAzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAlineacionAlAzarActionPerformed(evt);
            }
        });
        jPanel1.add(jAlineacionAlAzar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 130, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEquiposActionPerformed
                String team = jEquipos.getSelectedItem().toString();
                equipo = new Equipo(team.substring(0, 3));
                try {
                        FileReader fichero = new FileReader(team);
                        BufferedReader bR = new BufferedReader(fichero);
                        bR.readLine();
                        bR.readLine();
                        String jugador;
                        while ((jugador = bR.readLine()) != null) {
                                Jugador j = new Jugador(jugador, team);
                                equipo.anadirJugador(j);
                        }
                        bR.close();
                } catch (FileNotFoundException ex) {
                        System.out.println("Error");
                } catch (IOException ex) {
                        System.out.println("Error 2");
                }
    }//GEN-LAST:event_jEquiposActionPerformed

    private void jAlineacionAlAzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAlineacionAlAzarActionPerformed
                Alineacion alineacion = new Alineacion(equipo);
                alineacion.crearAlineacionRandom();
                System.out.println(alineacion);
    }//GEN-LAST:event_jAlineacionAlAzarActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
                /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(AlineacionAlAzar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(AlineacionAlAzar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(AlineacionAlAzar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(AlineacionAlAzar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
                //</editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                try {
                                        new AlineacionAlAzar().setVisible(true);
                                } catch (IOException ex) {
                                        System.out.println("Error");
                                }
                        }
                });
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAlineacionAlAzar;
    private javax.swing.JComboBox<String> jEquipos;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
