/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazGrafica;
import Contenedor.Contenedor;
import EquipoDep.*;
/**
 *
 * @author Antonio
 */
public class SumarFit extends javax.swing.JDialog {
    Contenedor liga;
    /**
     * Creates new form SumarFit
     */
    public SumarFit(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public SumarFit(java.awt.Frame parent, boolean modal, Contenedor lAux) {
        super(parent, modal);
        initComponents();
        liga = lAux;
        for (Equipo e:liga.getEquipos()){
            jComboBox1.addItem(e.getAbrev());
        }
        this.setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSumarFit = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sumar Fit Equipo");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSumarFit.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jSumarFit.setText("Sumar Fit");
        jSumarFit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSumarFitActionPerformed(evt);
            }
        });
        getContentPane().add(jSumarFit, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 100, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 70, 90, -1));

        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 130, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dsfsdfds_2.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -350, 320, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSumarFitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSumarFitActionPerformed
        liga.buscarEquipo(jComboBox1.getSelectedItem().toString()).sumarFit(Integer.parseInt(jTextField1.getText()));
    }//GEN-LAST:event_jSumarFitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SumarFit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SumarFit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SumarFit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SumarFit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SumarFit dialog = new SumarFit(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JButton jSumarFit;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
