/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paneles;

import VPrincipal.ESO_Management_v2;

/**
 *
 * @author Antonio
 */
public class contenedorPpal extends javax.swing.JPanel {

        CuadriculaBotones deportiva, financiera;

        /**
         * Creates new form contenedorPpal
         */
        public contenedorPpal(ESO_Management_v2 vPrincipal) {
                initComponents();
                deportiva = new CuadriculaBotones("Parte deportiva");
                financiera = new CuadriculaBotones("Parte financiera");
                deportiva.addBoton("Mostrar Plantillas Equipos", "mPlantillas", vPrincipal);
                deportiva.addBoton("Mostrar Selecciones Mundial", "mSeleccionesLiga", vPrincipal);
                deportiva.addBoton("Mostrar Todas Las Selecciones", "mSelecciones", vPrincipal);
                financiera.addBoton("Salarios", "salarios", vPrincipal);
                financiera.addBoton("Salarios", "salarios", vPrincipal);
                financiera.addBoton("Salarios", "salarios", vPrincipal);
                deportivo.add(deportiva);
                financiero.add(financiera);
        }

        /**
         * This method is called from within the constructor to
         * initialize the form. WARNING: Do NOT modify this code. The
         * content of this method is always regenerated by the Form
         * Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                deportivo = new javax.swing.JPanel();
                financiero = new javax.swing.JPanel();

                setLayout(new java.awt.GridLayout(1, 0));

                deportivo.setLayout(new java.awt.BorderLayout());
                add(deportivo);

                financiero.setLayout(new java.awt.BorderLayout());
                add(financiero);
        }// </editor-fold>//GEN-END:initComponents

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JPanel deportivo;
        private javax.swing.JPanel financiero;
        // End of variables declaration//GEN-END:variables
}
