/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paneles;

import AccionesBotones.*;
import java.util.*;
import javax.swing.JLabel;

/**
 *
 * @author Antonio
 */
public class CuadriculaBotones extends AbstractPanel {

        private HashMap<String, PanelConBoton> botones;
        private int nBotones;

        /**
         * Creates new form CuadriculaBotones
         */
        public CuadriculaBotones() {
                initComponents();
                botones = new HashMap<>();
                nBotones = 0;

        }

        public CuadriculaBotones(String titulo) {
                initComponents();
                botones = new HashMap<>();
                nBotones = 0;
                jLabel2.setText(titulo);

        }

        public HashMap<String, PanelConBoton> getBotones() {
                return botones;
        }

        public JLabel getTitulo() {
                return jLabel2;
        }

        public void addBoton(String nombreBoton, String comando, Acciones manejador) {
                java.awt.GridBagConstraints gridBagConstraints;
                PanelConBoton boton = new PanelConBoton(nombreBoton, comando);
                boton.setPadre(this);
                boton.setActionListener(manejador);
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridy = 1 + nBotones / 2;
                if (nBotones % 2 == 0) {
                        gridBagConstraints.gridx = 0;
                } else {
                        gridBagConstraints.gridx = 1;
                }
                gridBagConstraints.ipady = 240;
                gridBagConstraints.weightx = 1;
                gridBagConstraints.weighty = 1;
                gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
                add(boton, gridBagConstraints);
                botones.put(nombreBoton, boton);
                nBotones++;
        }

        public void removeBoton() {

        }

        /**
         * This method is called from within the constructor to
         * initialize the form. WARNING: Do NOT modify this code. The
         * content of this method is always regenerated by the Form
         * Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {
                java.awt.GridBagConstraints gridBagConstraints;

                jLabel2 = new javax.swing.JLabel();

                setLayout(new java.awt.GridBagLayout());

                jLabel2.setText("jLabel2");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 0;
                gridBagConstraints.gridy = 0;
                gridBagConstraints.gridwidth = 2;
                gridBagConstraints.ipady = 30;
                gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
                add(jLabel2, gridBagConstraints);
        }// </editor-fold>//GEN-END:initComponents

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel jLabel2;
        // End of variables declaration//GEN-END:variables
}
