/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paneles;

import static javax.swing.JTabbedPane.*;
import static javax.swing.SwingConstants.LEFT;
import program.model.Equipo.Roster;

/**
 *
 * @author Antonio
 */
public class MostrarRoster extends AbstractPanel {

        /**
         * Creates new form MostrarRoster
         */
        public MostrarRoster() {
                initComponents();
        }

        public MostrarRoster(Roster equipo) {
                this();

                pestanasRoster.setTabPlacement(LEFT);
                pestanasRoster.addTab("Prueba 1", null, null, "Esta es la prueba 1");
                pestanasRoster.addTab("Prueba 1", null, null, "Esta es la prueba 1");
                pestanasRoster.addTab("Prueba 1", null, null, "Esta es la prueba 1");
                pestanasRoster.addTab("Prueba 1", null, null, "Esta es la prueba 1");
                pestanasRoster.addTab("Prueba 1", null, null, "Esta es la prueba 1");
                pestanasRoster.addTab("Prueba 1", null, null, "Esta es la prueba 1");
                pestanasRoster.addTab("Prueba 1", null, null, "Esta es la prueba 1");
                pestanasRoster.addTab("Prueba 1", null, null, "Esta es la prueba 1");
                pestanasRoster.addTab("Prueba 1", null, null, "Esta es la prueba 1");
                pestanasRoster.addTab("Prueba 1", null, null, "Esta es la prueba 1");
                pestanasRoster.addTab("Prueba 1", null, null, "Esta es la prueba 1");
                pestanasRoster.addTab("Prueba 1", null, null, "Esta es la prueba 1");
                pestanasRoster.addTab("Prueba 1", null, null, "Esta es la prueba 1");
                pestanasRoster.addTab("Prueba 1", null, null, "Esta es la prueba 1");
                pestanasRoster.addTab("Prueba 1", null, null, "Esta es la prueba 1");
                pestanasRoster.addTab("Prueba 1", null, null, "Esta es la prueba 1");
                pestanasRoster.addTab("Prueba 1", null, null, "Esta es la prueba 1");
                pestanasRoster.addTab("Prueba 1", null, null, "Esta es la prueba 1");
                pestanasRoster.addTab("Prueba 1", null, null, "Esta es la prueba 1");
                pestanasRoster.addTab("Prueba 1", null, null, "Esta es la prueba 1");
                pestanasRoster.addTab("Prueba 1", null, null, "Esta es la prueba 1");
                pestanasRoster.addTab("Prueba 1", null, null, "Esta es la prueba 1");
                pestanasRoster.addTab("Prueba 1", null, null, "Esta es la prueba 1");
                pestanasRoster.addTab("Prueba 1", null, null, "Esta es la prueba 1");
                pestanasRoster.addTab("Prueba 1", null, null, "Esta es la prueba 1");
                pestanasRoster.addTab("Prueba 1", null, null, "Esta es la prueba 1");
                pestanasRoster.addTab("Prueba 1", null, null, "Esta es la prueba 1");
                pestanasRoster.addTab("Prueba 1", null, null, "Esta es la prueba 1");

                pestanasRoster.setTabLayoutPolicy(SCROLL_TAB_LAYOUT);
                //plantillaLabel.setText("<html>" + equipo.escribirHTML() + "</html>");
        }

        /**
         * This method is called from within the constructor to
         * initialize the form. WARNING: Do NOT modify this code. The
         * content of this method is always regenerated by the Form
         * Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {
                java.awt.GridBagConstraints gridBagConstraints;

                pestanasRoster = new javax.swing.JTabbedPane();

                setLayout(new java.awt.GridBagLayout());
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 0;
                gridBagConstraints.gridy = 0;
                gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
                gridBagConstraints.weightx = 1.0;
                gridBagConstraints.weighty = 1.0;
                add(pestanasRoster, gridBagConstraints);
        }// </editor-fold>//GEN-END:initComponents

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JTabbedPane pestanasRoster;
        // End of variables declaration//GEN-END:variables
}
