/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paneles;

import AccionesBotones.AccionesMostrarRoster;
import java.io.*;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import program.model.Equipo.Roster;

/**
 *
 * @author Antonio
 */
public class MostrarRoster extends AbstractPanel {

        private Roster equipo;

        /**
         * Creates new form MostrarRoster
         */
        public MostrarRoster() {
                initComponents();
        }

        public MostrarRoster(Roster equipo) {
                this();
                this.equipo = equipo;
                refrescarPlantilla();
        }

        public void refrescarPlantilla() {
                plantillaLabel.setText("<html>" + equipo.escribirHTML() + "</html>");
                plantillaLabel.setHorizontalTextPosition(SwingConstants.CENTER);
        }

        public void inicializarBotones() {
                ((AccionesMostrarRoster) this.getListeners().get("Mostrar Roster")).setLlamada(this);
                botonSalir.setActionCommand("salir");
                orderNombre.setActionCommand("ordenarNombre");
                orderEdad.setActionCommand("ordenarEdad");
                orderMedia.setActionCommand("ordenarMedia");
                orderRendimiento.setActionCommand("ordenarRendimiento");
                saveInformacion.setActionCommand("gInformacion");
                botonSalir.addActionListener(this.getListeners().get("Mostrar Roster"));
                orderNombre.addActionListener(this.getListeners().get("Mostrar Roster"));
                orderEdad.addActionListener(this.getListeners().get("Mostrar Roster"));
                orderMedia.addActionListener(this.getListeners().get("Mostrar Roster"));
                orderRendimiento.addActionListener(this.getListeners().get("Mostrar Roster"));
                saveInformacion.addActionListener(this.getListeners().get("Mostrar Roster"));
        }

        public void guardarTexto() {
                String texto = plantillaLabel.getText();
                texto = texto.replaceAll("<pre>", "");
                texto = texto.replaceAll("</pre>", "");
                texto = texto.replaceAll("<html>", "");
                texto = texto.replaceAll("</html>", "");
                texto = texto.replaceAll("<br>", "\n");
                String fileName = JOptionPane.showInputDialog("Introduce el nombre del archivo (sin extensión) donde quieres guardar la información (se guarda en .txt)", "");
                FileWriter fichero;
                try {
                        fichero = new FileWriter(fileName + ".txt");
                        PrintWriter pW = new PrintWriter(fichero);
                        String[] aux = texto.split("\n");
                        for (String s : aux) {
                                pW.println(s);
                        }
                        pW.close();
                        fichero.close();
                } catch (IOException ex) {
                        JOptionPane.showMessageDialog(null, ex.getMessage());
                }

        }

        public Roster getEquipo() {
                return equipo;
        }

        public void setEquipo(Roster equipo) {
                this.equipo = equipo;
        }

        /**
         * This method is called from within the constructor to
         * initialize the form. WARNING: Do NOT modify this code. The
         * content of this method is always regenerated by the Form
         * Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {
                java.awt.GridBagConstraints gridBagConstraints;

                contenedorPlantilla = new javax.swing.JScrollPane();
                jPanel1 = new javax.swing.JPanel();
                plantillaLabel = new javax.swing.JLabel();
                orderMedia = new javax.swing.JButton();
                orderNombre = new javax.swing.JButton();
                orderRendimiento = new javax.swing.JButton();
                orderEdad = new javax.swing.JButton();
                botonSalir = new javax.swing.JButton();
                saveInformacion = new javax.swing.JButton();
                jSeparator1 = new javax.swing.JSeparator();
                jSeparator2 = new javax.swing.JSeparator();

                setLayout(new java.awt.GridBagLayout());

                jPanel1.setLayout(new java.awt.GridBagLayout());

                plantillaLabel.setText("jLabel1");
                jPanel1.add(plantillaLabel, new java.awt.GridBagConstraints());

                contenedorPlantilla.setViewportView(jPanel1);

                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 1;
                gridBagConstraints.gridy = 0;
                gridBagConstraints.gridwidth = 11;
                gridBagConstraints.gridheight = 3;
                gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
                gridBagConstraints.weightx = 0.4;
                gridBagConstraints.weighty = 0.1;
                add(contenedorPlantilla, gridBagConstraints);

                orderMedia.setText("Ordenar por Media");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 0;
                gridBagConstraints.gridy = 0;
                gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
                gridBagConstraints.weightx = 0.1;
                gridBagConstraints.weighty = 0.1;
                add(orderMedia, gridBagConstraints);

                orderNombre.setText("Ordenar Por Nombre");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 0;
                gridBagConstraints.gridy = 1;
                gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
                gridBagConstraints.weightx = 0.1;
                gridBagConstraints.weighty = 0.1;
                add(orderNombre, gridBagConstraints);

                orderRendimiento.setText("Ordenar por Rendimiento");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 0;
                gridBagConstraints.gridy = 3;
                gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
                gridBagConstraints.weightx = 0.1;
                gridBagConstraints.weighty = 0.1;
                add(orderRendimiento, gridBagConstraints);

                orderEdad.setText("Ordenar por Edad");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 0;
                gridBagConstraints.gridy = 2;
                gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
                gridBagConstraints.weightx = 0.1;
                gridBagConstraints.weighty = 0.1;
                add(orderEdad, gridBagConstraints);

                botonSalir.setText("Salir");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 11;
                gridBagConstraints.gridy = 3;
                gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
                gridBagConstraints.weightx = 0.1;
                add(botonSalir, gridBagConstraints);

                saveInformacion.setText("Guardar Información");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 9;
                gridBagConstraints.gridy = 3;
                gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
                gridBagConstraints.weightx = 0.1;
                add(saveInformacion, gridBagConstraints);
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 8;
                gridBagConstraints.gridy = 3;
                gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
                gridBagConstraints.weightx = 0.1;
                add(jSeparator1, gridBagConstraints);
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 10;
                gridBagConstraints.gridy = 3;
                gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
                gridBagConstraints.weightx = 0.1;
                add(jSeparator2, gridBagConstraints);
        }// </editor-fold>//GEN-END:initComponents

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton botonSalir;
        private javax.swing.JScrollPane contenedorPlantilla;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JSeparator jSeparator1;
        private javax.swing.JSeparator jSeparator2;
        private javax.swing.JButton orderEdad;
        private javax.swing.JButton orderMedia;
        private javax.swing.JButton orderNombre;
        private javax.swing.JButton orderRendimiento;
        private javax.swing.JLabel plantillaLabel;
        private javax.swing.JButton saveInformacion;
        // End of variables declaration//GEN-END:variables
}
