/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paneles;

import java.awt.Image;
import java.awt.event.ActionListener;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author Antonio
 */
public class PanelConBoton extends AbstractPanel {

        /**
         * Creates new form PanelConBoton
         */
        public PanelConBoton() {
                initComponents();
        }

        public PanelConBoton(String nombreBoton, String comando) {
                this();
                jButton1.setText(nombreBoton);
                jButton1.setActionCommand(comando);

        }

        // Para crear el botón de salir
        public PanelConBoton(String nombreBoton) {
                this(nombreBoton, "salir");
        }

        public JButton getBoton() {
                return jButton1;
        }

        public void setActionListener(ActionListener listener) {
                this.jButton1.addActionListener(listener);
        }

        public void anadirImagen(URL pathImagen, URL pathVacia) {
                ImageIcon escudo = new ImageIcon(pathVacia);
                if (pathImagen != null) {
                        escudo = new ImageIcon(pathImagen);
                }
                escudo.setImage(escudo.getImage().getScaledInstance(80, 80, Image.SCALE_DEFAULT));
                this.getBoton().setIcon(escudo);
        }

        /*jButton4.setText("jButton4");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 0;
                gridBagConstraints.gridy = 1;
                gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
                gridBagConstraints.weightx = 0.1;
                gridBagConstraints.weighty = 0.1;
                add(jButton4, gridBagConstraints);
         */
        /**
         * This method is called from within the constructor to
         * initialize the form. WARNING: Do NOT modify this code. The
         * content of this method is always regenerated by the Form
         * Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jButton1 = new javax.swing.JButton();

                setLayout(new java.awt.BorderLayout());

                jButton1.setText("jButton1");
                add(jButton1, java.awt.BorderLayout.CENTER);
        }// </editor-fold>//GEN-END:initComponents

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jButton1;
        // End of variables declaration//GEN-END:variables
}
