/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazGrafica;
import Contenedor.Contenedor;
import EquipoDep.*;
import java.io.*;
import java.text.*;
import java.time.LocalDate;
import java.util.*;
import java.util.logging.*;
import javax.swing.JOptionPane;
/**
 *
 * @author ManuelFG
 */
public class Interfaz extends javax.swing.JFrame {
    double rMedioGk, rMedioDf, rMedioDm, rMedioMf, rMedioAm, rMedioFw;
    Contenedor liga;
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        liga = new Contenedor();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPruebaBonus = new javax.swing.JButton();
                jTodosJugadoresPos = new javax.swing.JButton();
                jNumJugadores = new javax.swing.JButton();
                jMensajes = new javax.swing.JButton();
                jClasificacion = new javax.swing.JButton();
                jElo = new javax.swing.JButton();
                jSalarios = new javax.swing.JButton();
                jSimAutomatico = new javax.swing.JButton();
                jTodosJugadoresEdad = new javax.swing.JButton();
                jRendimiento = new javax.swing.JButton();
                jPotenciales = new javax.swing.JButton();
                jCargarSelecciones = new javax.swing.JButton();
                jGuardarJugadoresAZ = new javax.swing.JButton();
                jButton1 = new javax.swing.JButton();
                jEntrenamientos = new javax.swing.JButton();
                jLabelIcono = new javax.swing.JLabel();
                jLabelParcelaDeportiva = new javax.swing.JLabel();
                jButtonCargarPlantillas = new javax.swing.JButton();
                jButtonTraspasarJugadores = new javax.swing.JButton();
                jButtonSelecciones = new javax.swing.JButton();
                jButtonBonusDeMinutos = new javax.swing.JButton();
                jButtonEstadisticas = new javax.swing.JButton();
                jButtonMostrarPlantillas = new javax.swing.JButton();
                jButton2 = new javax.swing.JButton();
                jButton3 = new javax.swing.JButton();
                jSumarFit = new javax.swing.JButton();
                jLabelFondo = new javax.swing.JLabel();
                jLabel1 = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setUndecorated(true);
                getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jPruebaBonus.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
                jPruebaBonus.setText("Test Bonus nuevo Minutos");
                jPruebaBonus.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jPruebaBonusActionPerformed(evt);
                        }
                });
                getContentPane().add(jPruebaBonus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 230, -1));

                jTodosJugadoresPos.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
                jTodosJugadoresPos.setText("Guardar Todos Jugadores (Posicion)");
                jTodosJugadoresPos.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTodosJugadoresPosActionPerformed(evt);
                        }
                });
                getContentPane().add(jTodosJugadoresPos, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, 230, -1));

                jNumJugadores.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
                jNumJugadores.setText("Numero de jugadores por Equipo");
                jNumJugadores.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jNumJugadoresActionPerformed(evt);
                        }
                });
                getContentPane().add(jNumJugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 230, -1));

                jMensajes.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
                jMensajes.setText("Mensajes automaticos");
                jMensajes.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jMensajesActionPerformed(evt);
                        }
                });
                getContentPane().add(jMensajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, 230, -1));

                jClasificacion.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
                jClasificacion.setText("Clasificacion");
                jClasificacion.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jClasificacionActionPerformed(evt);
                        }
                });
                getContentPane().add(jClasificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 230, -1));

                jElo.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
                jElo.setText("Elo Equipos");
                jElo.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jEloActionPerformed(evt);
                        }
                });
                getContentPane().add(jElo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, 230, -1));

                jSalarios.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
                jSalarios.setText("Salarios");
                jSalarios.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jSalariosActionPerformed(evt);
                        }
                });
                getContentPane().add(jSalarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 230, -1));

                jSimAutomatico.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
                jSimAutomatico.setText("Simular Automaticamente");
                jSimAutomatico.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jSimAutomaticoActionPerformed(evt);
                        }
                });
                getContentPane().add(jSimAutomatico, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 230, -1));

                jTodosJugadoresEdad.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
                jTodosJugadoresEdad.setText("Guardar Todos Jugadores (Edad)");
                jTodosJugadoresEdad.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTodosJugadoresEdadActionPerformed(evt);
                        }
                });
                getContentPane().add(jTodosJugadoresEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 230, -1));

                jRendimiento.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
                jRendimiento.setText("Rendimiento Equipos");
                jRendimiento.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jRendimientoActionPerformed(evt);
                        }
                });
                getContentPane().add(jRendimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 230, -1));

                jPotenciales.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
                jPotenciales.setText("Potenciales");
                jPotenciales.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jPotencialesActionPerformed(evt);
                        }
                });
                getContentPane().add(jPotenciales, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 230, -1));

                jCargarSelecciones.setBackground(new java.awt.Color(0, 102, 255));
                jCargarSelecciones.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
                jCargarSelecciones.setForeground(new java.awt.Color(255, 255, 255));
                jCargarSelecciones.setText("Cargar Selecciones");
                jCargarSelecciones.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jCargarSeleccionesActionPerformed(evt);
                        }
                });
                getContentPane().add(jCargarSelecciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 230, -1));

                jGuardarJugadoresAZ.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
                jGuardarJugadoresAZ.setText("Guardar Todos Jugadores (A-Z)");
                jGuardarJugadoresAZ.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jGuardarJugadoresAZActionPerformed(evt);
                        }
                });
                getContentPane().add(jGuardarJugadoresAZ, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 230, -1));

                jButton1.setBackground(new java.awt.Color(0, 102, 255));
                jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                jButton1.setForeground(new java.awt.Color(255, 255, 255));
                jButton1.setText("Salir");
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                        }
                });
                getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, -1));

                jEntrenamientos.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
                jEntrenamientos.setText("Entrenamientos");
                jEntrenamientos.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jEntrenamientosActionPerformed(evt);
                        }
                });
                getContentPane().add(jEntrenamientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 230, -1));

                jLabelIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/teggs.png"))); // NOI18N
                getContentPane().add(jLabelIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 120));

                jLabelParcelaDeportiva.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                jLabelParcelaDeportiva.setText("Parcela Deportiva");
                getContentPane().add(jLabelParcelaDeportiva, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

                jButtonCargarPlantillas.setBackground(new java.awt.Color(0, 102, 255));
                jButtonCargarPlantillas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
                jButtonCargarPlantillas.setForeground(new java.awt.Color(255, 255, 255));
                jButtonCargarPlantillas.setText("Cargar Plantillas");
                jButtonCargarPlantillas.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButtonCargarPlantillasActionPerformed(evt);
                        }
                });
                getContentPane().add(jButtonCargarPlantillas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 230, -1));

                jButtonTraspasarJugadores.setBackground(new java.awt.Color(0, 102, 255));
                jButtonTraspasarJugadores.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
                jButtonTraspasarJugadores.setText("Traspasar jugadores");
                jButtonTraspasarJugadores.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButtonTraspasarJugadoresActionPerformed(evt);
                        }
                });
                getContentPane().add(jButtonTraspasarJugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 230, -1));

                jButtonSelecciones.setBackground(new java.awt.Color(0, 102, 255));
                jButtonSelecciones.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
                jButtonSelecciones.setText("Selecciones");
                jButtonSelecciones.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButtonSeleccionesActionPerformed(evt);
                        }
                });
                getContentPane().add(jButtonSelecciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 230, -1));

                jButtonBonusDeMinutos.setBackground(new java.awt.Color(0, 102, 255));
                jButtonBonusDeMinutos.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
                jButtonBonusDeMinutos.setText("Bonus de Minutos");
                jButtonBonusDeMinutos.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButtonBonusDeMinutosActionPerformed(evt);
                        }
                });
                getContentPane().add(jButtonBonusDeMinutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 230, 30));

                jButtonEstadisticas.setBackground(new java.awt.Color(0, 102, 255));
                jButtonEstadisticas.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
                jButtonEstadisticas.setText("Estadisticas");
                jButtonEstadisticas.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButtonEstadisticasActionPerformed(evt);
                        }
                });
                getContentPane().add(jButtonEstadisticas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 230, -1));

                jButtonMostrarPlantillas.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
                jButtonMostrarPlantillas.setText("Mostrar Plantillas");
                jButtonMostrarPlantillas.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButtonMostrarPlantillasActionPerformed(evt);
                        }
                });
                getContentPane().add(jButtonMostrarPlantillas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 230, -1));

                jButton2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
                jButton2.setText("Guardar Plantillas");
                jButton2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton2ActionPerformed(evt);
                        }
                });
                getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 230, -1));

                jButton3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
                jButton3.setText("Guardar Todos Jugadores (Media)");
                jButton3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton3ActionPerformed(evt);
                        }
                });
                getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 230, -1));

                jSumarFit.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
                jSumarFit.setText("Sumar Fit Equipo");
                jSumarFit.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jSumarFitActionPerformed(evt);
                        }
                });
                getContentPane().add(jSumarFit, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 230, -1));

                jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dsfsdfds_2.png"))); // NOI18N
                getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 510, 610));

                jLabel1.setText("jLabel1");
                getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, -1));

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonMostrarPlantillasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarPlantillasActionPerformed
        Collections.sort(liga.getEquipos(), new CompareEquiposAZ());
        new MostrarPlantillas(this, true, liga).setVisible(true);
    }//GEN-LAST:event_jButtonMostrarPlantillasActionPerformed

    private void jButtonCargarPlantillasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCargarPlantillasActionPerformed
       try {
            liga = new Contenedor();
            liga.cargarDatos();
        } catch (IOException ex) {
            new JDialogError(this, true).setVisible(true);
        }
    }//GEN-LAST:event_jButtonCargarPlantillasActionPerformed

    private void jButtonTraspasarJugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTraspasarJugadoresActionPerformed
        Collections.sort(liga.getEquipos(), new CompareEquiposAZ());
        new TraspasarJugadores(this, true, liga).setVisible(true);
    }//GEN-LAST:event_jButtonTraspasarJugadoresActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            liga.guardarEquipos();
        } catch (IOException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonSeleccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeleccionesActionPerformed
        new Selecciones (this, true, liga).setVisible(true);
    }//GEN-LAST:event_jButtonSeleccionesActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            File todosJugadores = new File ("Todos los jugadores");
            todosJugadores.mkdir();
            FileWriter fichero = new FileWriter ("\\" + todosJugadores + "\\Todos los Jugadores Media.txt");
            BufferedWriter bw = new BufferedWriter (fichero);
            PrintWriter pW = new PrintWriter(bw);
            liga.escribirCabecera(pW);
            ArrayList <Jugador> roster = liga.getJugadores();
            Collections.sort(roster, new CompareJugadores());
            for(Jugador j: roster){
                pW.println(j.toString() + " (" + j.getEquipo().toLowerCase() + ")");
            }
            pW.close();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jSumarFitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSumarFitActionPerformed
        Collections.sort(liga.getEquipos(), new CompareEquiposAZ());
        try {
            FileReader fit = new FileReader ("Fisio.dir");
            BufferedReader bR = new BufferedReader (fit);
            String [] cadena;
            String s;
            while ((s = bR.readLine())!= null){
                cadena = s.split("\\s+");
                int nFit = Integer.parseInt(cadena[0]);
                int i;
                for (i = 1; i<cadena.length; i++){
                    liga.buscarEquipo(cadena[i]).sumarFit(nFit);
                }
            }
        } catch (FileNotFoundException ex) {
            System.out.println("Error");
        } catch (IOException ex) {
            System.out.println("Error");
        }
        //new SumarFit(this, true, liga).setVisible(true);
    }//GEN-LAST:event_jSumarFitActionPerformed

    private void jEntrenamientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEntrenamientosActionPerformed
        Collections.sort(liga.getEquipos(), new CompareEquiposAZ());
        int semanas = Integer.parseInt(JOptionPane.showInputDialog(this, "Elige cuantas semanas se entrenarán", "Elegir semanas", 0));
        try {
            FileReader entrenamientos = new FileReader ("Entrenamientos.dir");
            BufferedReader bR = new BufferedReader (entrenamientos);
            String s;
            Calendar fecha = GregorianCalendar.getInstance();
            int dia = fecha.get(Calendar.DAY_OF_MONTH);
            int mes = fecha.get(Calendar.MONTH) + 1;
            int año = fecha.get(Calendar.YEAR);
            int hora = fecha.get(Calendar.HOUR_OF_DAY);
            int min = fecha.get(Calendar.MINUTE);
            while ((s = bR.readLine())!= null){
                String [] cadena = s.split("\\s+");
                int St = Integer.parseInt(cadena[0]);
                int Tk = Integer.parseInt(cadena[1]);
                int Ps = Integer.parseInt(cadena[2]);
                int Sh = Integer.parseInt(cadena[3]);
                File carpeta = new File ("Entrenamientos");
                carpeta.mkdir();
                int i;
                for (i = 4; i<cadena.length; i++){
                    try {
                        Equipo resultado = liga.buscarEquipo(cadena[i]);
                        FileWriter fichero = new FileWriter ("\\" + carpeta + "\\logEntrenamientos" + dia + "-" + mes + "-" + año + ".txt", true);
                        BufferedWriter bW = new BufferedWriter (fichero);
                        PrintWriter pW = new PrintWriter (bW);
                        String horaAct = hora + ":" + min;
                        pW.println(horaAct + " - Equipo: " + resultado.getAbrev());
                        pW.println();
                        for (Jugador j: resultado.getRoster()){
                            Habilidad [] h = {new Habilidad (j.getGkSkills()), new Habilidad (j.getDfSkills()), new Habilidad(j.getMfSkills()), new Habilidad(j.getFwSkills())};
                            if (j.getPosicion() == Jugador.Posicion.gk){
                                j.getGkSkills().setExp(j.getGkSkills().getExp() + semanas * St);
                                if (j.getGkSkills().getMedia()<h[0].getMedia()){
                                    pW.println(j.getNombre() + " (" + j.getEquipo().toLowerCase() + ") ha bajado su media de portero de " + h[0].getMedia() + " a " + j.getGkSkills().getMedia());
                                }else if (j.getGkSkills().getMedia()>h[0].getMedia()){
                                    pW.println(j.getNombre() + " (" + j.getEquipo().toLowerCase() + ") ha subido su media de portero de " + h[0].getMedia() + " a " + j.getGkSkills().getMedia());
                                }
                            }else{
                                j.getDfSkills().setExp(j.getDfSkills().getExp() + semanas * Tk);
                                if (j.getDfSkills().getMedia()<h[1].getMedia()){
                                    pW.println(j.getNombre() + " (" + j.getEquipo().toLowerCase() + ") ha bajado su media de defensa de " + h[1].getMedia() + " a " + j.getDfSkills().getMedia());
                                }else if (j.getDfSkills().getMedia()>h[1].getMedia()){
                                    pW.println(j.getNombre() + " (" + j.getEquipo().toLowerCase() + ") ha subido su media de defensa de " + h[1].getMedia() + " a " + j.getDfSkills().getMedia());
                                }
                                j.getMfSkills().setExp(j.getMfSkills().getExp() + semanas * Ps);
                                if (j.getMfSkills().getMedia()<h[2].getMedia()){
                                    pW.println(j.getNombre() + " (" + j.getEquipo().toLowerCase() + ") ha bajado su media de medio de " + h[2].getMedia() + " a " + j.getMfSkills().getMedia());
                                }else if (j.getMfSkills().getMedia()>h[2].getMedia()){
                                    pW.println(j.getNombre() + " (" + j.getEquipo().toLowerCase() + ") ha subido su media de medio de " + h[2].getMedia() + " a " + j.getMfSkills().getMedia());
                                }
                                j.getFwSkills().setExp(j.getFwSkills().getExp() + semanas * Sh);
                                if (j.getFwSkills().getMedia()<h[3].getMedia()){
                                    pW.println(j.getNombre() + " (" + j.getEquipo().toLowerCase() + ") ha bajado su media de delantero de " + h[3].getMedia() + " a " + j.getFwSkills().getMedia());
                                }else if (j.getFwSkills().getMedia()>h[3].getMedia()){
                                    pW.println(j.getNombre() + " (" + j.getEquipo().toLowerCase() + ") ha subido su media de delantero de " + h[3].getMedia() + " a " + j.getFwSkills().getMedia());
                                }
                            }
                            j.definirPosicion();
                            j.definirPosInt();
                            j.definirMedias();
                            j.definirSalario();
                        }
                        pW.println();
                        pW.println("---------------------------------------------------------------------------");
                        pW.println();
                        pW.close();
                    } catch (IOException ex) {
                        Logger.getLogger(jEntrenamientos.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    ;
                }
                
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         
        // new jEntrenamientos(this, true, liga).setVisible(true);
    }//GEN-LAST:event_jEntrenamientosActionPerformed

    private void jGuardarJugadoresAZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGuardarJugadoresAZActionPerformed
       try {
            File todosJugadores = new File ("Todos los jugadores");
            todosJugadores.mkdir();
            FileWriter fichero = new FileWriter ("\\" + todosJugadores + "\\Todos los Jugadores A-Z.txt");
            BufferedWriter bw = new BufferedWriter (fichero);
            PrintWriter pW = new PrintWriter(bw);
            liga.escribirCabecera(pW);
            ArrayList <Jugador> roster = liga.getJugadores();
            Collections.sort(roster);
            for(Jugador j: roster){
                pW.println(j.toString() + " (" + j.getEquipo().toLowerCase() + ")");
            }
            pW.close();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_jGuardarJugadoresAZActionPerformed

    private void jCargarSeleccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCargarSeleccionesActionPerformed
        try {
            liga.cargarSelecciones();
        } catch (IOException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jCargarSeleccionesActionPerformed

    private void jButtonBonusDeMinutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBonusDeMinutosActionPerformed
        BonusMinutos b = liga.getBonus().get(0);
        System.out.println(b.getBonus().get(1).get(0)[3]);
        File carpetaBonus = new File ("Bonus de Minutos");
        carpetaBonus.mkdir();
        try {
            FileWriter logBonus = new FileWriter ("\\" + carpetaBonus + "\\logBonus.txt");
            BufferedWriter bW = new BufferedWriter (logBonus);
            PrintWriter pW = new PrintWriter (bW);
            for (Equipo e:liga.getEquipos()){
                for(Jugador j:e.getRoster()){
                    int media, edad, min;
                    media = Math.abs(16 - j.getMedias()[0]);
                    int aux = j.getEdad();
                    if (aux <=20) edad = 0;
                    else if (aux <24) edad = 1;
                    else if (aux <27) edad = 2;
                    else if (aux <30) edad = 3;
                    else if (aux <34) edad = 4;
                    else if (aux <36) edad = 5;
                    else edad = 6;
                    aux = j.getStats().getMinutos();
                    if (aux <= 1500) min = 0;
                    else if (aux <=2100) min = 1;
                    else if (aux <=2700) min = 2;
                    else if (aux <=3499) min = 3;
                    else if (aux <=4099) min = 4;
                    else min = 5;
                    int expAModificar = b.getBonus().get(media).get(edad)[min];
                    int antMedia = 0, antExp = 0, nMedia = 0, nExp = 0;
                    String posicion = "", stat = "";
                    switch(j.getPosInt()){
                        case 1:
                            antMedia = j.getGkSkills().getMedia();
                            antExp = j.getGkSkills().getExp();
                            j.getGkSkills().setExp(antExp + expAModificar);
                            nMedia = j.getGkSkills().getMedia();
                            nExp = j.getGkSkills().getExp();
                            posicion = "St";
                            stat = "Gk";
                        break;
                        case 2:
                            antMedia = j.getDfSkills().getMedia();
                            antExp = j.getDfSkills().getExp();
                            j.getDfSkills().setExp(antExp + expAModificar);
                            nMedia = j.getDfSkills().getMedia();
                            nExp = j.getDfSkills().getExp();
                            posicion = "Tk";
                            stat = "Df";
                        break;
                        case 3:
                            antMedia = j.getMfSkills().getMedia();
                            antExp = j.getMfSkills().getExp();
                            j.getMfSkills().setExp(antExp + expAModificar);
                            nMedia = j.getMfSkills().getMedia();
                            nExp = j.getMfSkills().getExp();
                            posicion = "Ps";
                            stat = "Mf";
                        break;
                        case 4:
                            antMedia = j.getMfSkills().getMedia();
                            antExp = j.getMfSkills().getExp();
                            j.getMfSkills().setExp(antExp + expAModificar);
                            nMedia = j.getMfSkills().getMedia();
                            nExp = j.getMfSkills().getExp();
                            posicion = "Ps";
                            stat = "Mf";
                        break;
                        case 5:
                            antMedia = j.getMfSkills().getMedia();
                            antExp = j.getMfSkills().getExp();
                            j.getMfSkills().setExp(antExp + expAModificar);
                            nMedia = j.getMfSkills().getMedia();
                            nExp = j.getMfSkills().getExp();
                            posicion = "Ps";
                            stat = "Mf";
                        break;
                        case 6:
                            antMedia = j.getFwSkills().getMedia();
                            antExp = j.getFwSkills().getExp();
                            j.getFwSkills().setExp(antExp + expAModificar);
                            nMedia = j.getFwSkills().getMedia();
                            nExp = j.getFwSkills().getExp();
                            posicion = "Sh";
                            stat = "Fw";
                        break;
                    }
                    String variacion = "", bajadaMedia = "";
                    int cambio;
                    if (antMedia<nMedia){
                        variacion = "ha subido";
                        cambio = (nMedia - antMedia)*1000 - Math.abs(nExp - antExp);
                        bajadaMedia = "Subiendo " + (nMedia - antMedia) + " media como " + stat + ".";
                    }else if (antMedia>nMedia){
                        variacion = "ha bajado";
                        cambio = Math.abs(antMedia-nMedia)*1000 - (nExp - antExp);
                        bajadaMedia = "Bajando " + (antMedia - nMedia) + " media como " + stat + ".";
                    }else{
                        if (antExp<nExp){
                            variacion = "ha subido";
                            cambio = nExp - antExp;
                        }else if (antExp>nExp){
                            variacion = "ha bajado";
                            cambio = antExp - nExp;
                        }else{
                            variacion = "ha ganado";
                            cambio = 0;
                        }
                    }
                    pW.println(j.getNombre() + " (" + j.getEquipo().toLowerCase() + ") " + variacion + " " + expAModificar + " pts de exp como " + stat + ". " + bajadaMedia);
                }
            }
            pW.close();
        } catch (IOException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButtonBonusDeMinutosActionPerformed

    private void jButtonEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEstadisticasActionPerformed
        String [] stats = {"goles", "goles por minuto", "goles por partido",
                           "goles encajados", "goles encajados por mninuto", "goles encajados por partido",
                           "paradas", "paradas por minuto", "paradas por partido",
                           "tiros", "tiros fallados", "tiros por minuto" , "tiros por partido",
                           "pases", "pases por minuto", "pases por partido",
                           "tackles", "tackles por minuto", "tackles por partido",
                           "asistencias", "asistencias por minuto", "asistencias por partido",
                           "partidos jugados", "partidos como suplente", "minutos", "minutos (sin porteros)", "mom", "dp",};
        int partidos = Integer.parseInt(JOptionPane.showInputDialog(this, "Elige cuantos partidos de estadistica se tendran en cuenta", "Elegir partidos", 0));
        int jugadores = Integer.parseInt(JOptionPane.showInputDialog(this, "Elige cuantos jugadores se mostraran", "Elegir jugadores", 0));
        try {
            File directorio = new File ("Estadisticas");
            directorio.mkdir();
            FileWriter fichero = new FileWriter ("\\" + directorio + "\\Estadisticas.txt");
            BufferedWriter bW = new BufferedWriter (fichero);
            PrintWriter pW = new PrintWriter (bW);
            ArrayList <Jugador> jugadoresMinPartidos = new ArrayList <Jugador>();
            for (Jugador j: liga.getJugadores()){
                if (j.getStats().getJugados() >= partidos){
                    jugadoresMinPartidos.add(new Jugador (j));
                }
            }
            for (int i = 0; i<stats.length; i++){
                System.out.println(i);
                pW.println(stats[i].toUpperCase());
                pW.println("--------------------------------------------------------------------");
                Collections.sort(jugadoresMinPartidos, new CompareStats(i));
                int l = 0;
                int k = 0;
                while(l<jugadores && k<jugadoresMinPartidos.size()){
                    Jugador j = jugadoresMinPartidos.get(k);
                    DecimalFormat df = new DecimalFormat("0.000");
                    if ((((i/3 == 1) || (i/3 == 2)) && j.getPosInt() != 1)||(i==25) && (j.getPosInt()==1)) {
                        k++;
                    }else{
                        switch (i){
                            case 0:
                                pW.println(l+1 + ". " + j.getNombre() + " (" + j.getEquipo().toLowerCase() + "), " + j.getStats().getGoles() + " " + stats[i] + ".");
                            break;
                            case 1:
                                pW.println(l+1 + ". " + j.getNombre() + " (" + j.getEquipo().toLowerCase() + "), " + df.format((double)j.getStats().getGoles()/(double)j.getStats().getMinutos())
                                + " " + stats[i] + ".");
                            break;
                            case 2:
                                pW.println(l+1 + ". " + j.getNombre() + " (" + j.getEquipo().toLowerCase() + "), " + df.format((double)j.getStats().getGoles()/(double)j.getStats().getJugados())
                                + " " + stats[i] + ".");
                            break;
                            case 3:
                                pW.println(l+1 + ". " + j.getNombre() + " (" + j.getEquipo().toLowerCase() + "), " + j.getStats().getEncajados() + " " + stats[i] + ".");
                            break;
                            case 4:
                                pW.println(l+1 + ". " + j.getNombre() + " (" + j.getEquipo().toLowerCase() + "), " + df.format((double)j.getStats().getEncajados()/(double)j.getStats().getMinutos())
                                + " " + stats[i] + ".");
                            break;
                            case 5:
                                pW.println(l+1 + ". " + j.getNombre() + " (" + j.getEquipo().toLowerCase() + "), " + df.format((double)j.getStats().getEncajados()/(double)j.getStats().getJugados())
                                + " " + stats[i] + ".");
                            break;
                            case 6:
                                pW.println(l+1 + ". " + j.getNombre() + " (" + j.getEquipo().toLowerCase() + "), " + j.getStats().getParadas() + " " + stats[i] + ".");
                            break;
                            case 7:
                                pW.println(l+1 + ". " + j.getNombre() + " (" + j.getEquipo().toLowerCase() + "), " + df.format((double)j.getStats().getParadas()/(double)j.getStats().getMinutos())
                                + " " + stats[i] + ".");
                            break;
                            case 8:
                                pW.println(l+1 + ". " + j.getNombre() + " (" + j.getEquipo().toLowerCase() + "), " + df.format((double)j.getStats().getParadas()/(double)j.getStats().getJugados())
                                + " " + stats[i] + ".");
                            break;
                            case 9:
                                pW.println(l+1 + ". " + j.getNombre() + " (" + j.getEquipo().toLowerCase() + "), " + j.getStats().getTiros() + " " + stats[i] + ".");
                            break;
                            case 10:
                                pW.println(l+1 + ". " + j.getNombre() + " (" + j.getEquipo().toLowerCase() + "), " + (j.getStats().getTiros() - j.getStats().getGoles()) + " " + stats[i] + ".");
                            break;
                            case 11:
                                pW.println(l+1 + ". " + j.getNombre() + " (" + j.getEquipo().toLowerCase() + "), " + df.format((double)j.getStats().getTiros()/(double)j.getStats().getMinutos())
                                + " " + stats[i] + ".");
                            break;
                            case 12:
                                pW.println(l+1 + ". " + j.getNombre() + " (" + j.getEquipo().toLowerCase() + "), " + df.format((double)j.getStats().getTiros()/(double)j.getStats().getJugados())
                                + " " + stats[i] + ".");
                            break;
                            case 13:
                                pW.println(l+1 + ". " + j.getNombre() + " (" + j.getEquipo().toLowerCase() + "), " + j.getStats().getPases() + " " + stats[i] + ".");
                            break;
                             case 14:
                                pW.println(l+1 + ". " + j.getNombre() + " (" + j.getEquipo().toLowerCase() + "), " + df.format((double)j.getStats().getPases()/(double)j.getStats().getMinutos())
                                + " " + stats[i] + ".");
                            break;
                            case 15:
                                pW.println(l+1 + ". " + j.getNombre() + " (" + j.getEquipo().toLowerCase() + "), " + df.format((double)j.getStats().getPases()/(double)j.getStats().getJugados())
                                + " " + stats[i] + ".");
                            break;
                            case 16:
                                pW.println(l+1 + ". " + j.getNombre() + " (" + j.getEquipo().toLowerCase() + "), " + j.getStats().getTackles() + " " + stats[i] + ".");
                            break;
                             case 17:
                                pW.println(l+1 + ". " + j.getNombre() + " (" + j.getEquipo().toLowerCase() + "), " + df.format((double)j.getStats().getTackles()/(double)j.getStats().getMinutos())
                                + " " + stats[i] + ".");
                            break;
                            case 18:
                                pW.println(l+1 + ". " + j.getNombre() + " (" + j.getEquipo().toLowerCase() + "), " + df.format((double)j.getStats().getTackles()/(double)j.getStats().getJugados())
                                + " " + stats[i] + ".");
                            break;
                            case 19:
                                pW.println(l+1 + ". " + j.getNombre() + " (" + j.getEquipo().toLowerCase() + "), " + j.getStats().getAsistencias() + " " + stats[i] + ".");
                            break;
                            case 20:
                                pW.println(l+1 + ". " + j.getNombre() + " (" + j.getEquipo().toLowerCase() + "), " + df.format((double)j.getStats().getAsistencias()/(double)j.getStats().getMinutos())
                                + " " + stats[i] + ".");
                            break;
                            case 21:
                                pW.println(l+1 + ". " + j.getNombre() + " (" + j.getEquipo().toLowerCase() + "), " + df.format((double)j.getStats().getAsistencias()/(double)j.getStats().getJugados())
                                + " " + stats[i] + ".");
                            break;
                            case 22:
                                pW.println(l+1 + ". " + j.getNombre() + " (" + j.getEquipo().toLowerCase() + "), " + j.getStats().getJugados() + " " + stats[i] + ".");
                            break;
                            case 23:
                                pW.println(l+1 + ". " + j.getNombre() + " (" + j.getEquipo().toLowerCase() + "), " + j.getStats().getSuplente() + " " + stats[i] + ".");
                            break;
                            case 24:
                                pW.println(l+1 + ". " + j.getNombre() + " (" + j.getEquipo().toLowerCase() + "), " + j.getStats().getMinutos() + " " + stats[i] + ".");
                            break;
                            case 25:
                                pW.println(l+1 + ". " + j.getNombre() + " (" + j.getEquipo().toLowerCase() + "), " + j.getStats().getMinutos() + " " + stats[i-1] + ".");
                            break;
                            case 26:
                                pW.println(l+1 + ". " + j.getNombre() + " (" + j.getEquipo().toLowerCase() + "), " + j.getStats().getMom() + " " + stats[i] + ".");
                            break;
                            case 27:
                                pW.println(l+1 + ". " + j.getNombre() + " (" + j.getEquipo().toLowerCase() + "), " + j.getStats().getDP() + " " + stats[i] + ".");
                            break;
                        }
                        l++;
                        k++;
                    }
                }
                pW.println("--------------------------------------------------------------------");
                pW.println();
            }
            pW.close();
        } catch (IOException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonEstadisticasActionPerformed

    private void jPotencialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPotencialesActionPerformed
        try {
            FileWriter potenciales = new FileWriter ("Potenciales.txt");
            BufferedWriter bW = new BufferedWriter (potenciales);
            PrintWriter pW = new PrintWriter (bW);
            for (Equipo e:liga.getEquipos()){
                e.calcularPotencial();
            }
            Collections.sort(liga.getEquipos(), new CompareEquipos());
            pW.println("POTENCIALES CLUBES ESO");
            pW.println("------------------------------------------------");
            DecimalFormat df = new DecimalFormat ("0.000");
            int num = 0;
            for (Equipo e: liga.getEquipos()){
                if (!e.getAbrev().toUpperCase().equals("LIB")){
                   num++;
                   pW.println(num + ". " + e.getAbrev().toUpperCase() + ": " + df.format(e.getPotencial()) + " puntos."); 
                }
            }
            pW.println("------------------------------------------------");
            pW.close();
        } catch (IOException ex) {
            System.out.println ("Error");
        }
    }//GEN-LAST:event_jPotencialesActionPerformed

    private void jTodosJugadoresEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTodosJugadoresEdadActionPerformed
       try {
            File todosJugadores = new File ("Todos los jugadores");
            todosJugadores.mkdir();
            FileWriter fichero = new FileWriter ("\\" + todosJugadores + "\\Todos los Jugadores Edad.txt");
            BufferedWriter bw = new BufferedWriter (fichero);
            PrintWriter pW = new PrintWriter(bw);
            liga.escribirCabecera(pW);
            ArrayList <Jugador> roster = liga.getJugadores();
            Collections.sort(roster, new CompareJugadoresEdad());
            for(Jugador j: roster){
                pW.println(j.toString() + " (" + j.getEquipo().toLowerCase() + ")");
            }
            pW.close();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_jTodosJugadoresEdadActionPerformed

    private void jRendimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRendimientoActionPerformed
       try {
            File directorio = new File ("Rendimiento");
            directorio.mkdir();
            FileWriter potenciales = new FileWriter ("\\" + directorio + "\\Rendimiento.txt");
            BufferedWriter bW = new BufferedWriter (potenciales);
            PrintWriter pW = new PrintWriter (bW);
            for (Equipo e:liga.getEquipos()){
                e.calcularRendimiento();
            }
            Collections.sort(liga.getEquipos(), new CompareEquiposRend());
            pW.println("RENDIMIENTO CLUBES ESO");
            pW.println("------------------------------------------------");
            DecimalFormat df = new DecimalFormat ("0.0");
            int num = 0;
            for (Equipo e: liga.getEquipos()){
                if (!e.getAbrev().toUpperCase().equals("LIB")){
                   num++;
                   pW.println(num + ". " + e.getAbrev().toUpperCase() + ": " + df.format(e.getRendimiento()) + " puntos."); 
                }
            }
            pW.println("------------------------------------------------");
            pW.close();
            String [] posiciones = {"mejores GK", "mejores DF", "mejores DM", "mejores MF", "mejores AM", "mejores FW"};
            int k = 0;
            for (String s: posiciones){
                k++;
                potenciales = new FileWriter ("\\" + directorio + "\\" + s + ".txt");
                bW = new BufferedWriter (potenciales);
                pW = new PrintWriter (bW);
                pW.println (s.toUpperCase());
                pW.println("------------------------------------------------");
                ArrayList <Jugador> jPosicion = new ArrayList <Jugador>();
                int i = 1;
                for (Jugador j:liga.getJugadores()){
                    if (j.getPosInt() == k)
                        jPosicion.add(j);
                }
                for (Jugador j: jPosicion){
                    j.calcularRendimiento();
                }
                Collections.sort(jPosicion, new CompareJugadoresRend());
                DecimalFormat df2 = new DecimalFormat ("0.000");
                for (Jugador j: jPosicion){
                    if (j.getStats().getMinutos()>0){
                        pW.println(i + ". " + j.getNombre() + " (" + j.getEquipo().toLowerCase() + "), " + df2.format(j.getRendimiento()) + " puntos");
                        i++;
                    }
                }
                pW.println("------------------------------------------------");
                double rMedio = 0;
                int jugadores = 0;
                int media = 16;
                for (Jugador j: jPosicion){
                    if (j.getStats().getMinutos()>0){
                        rMedio += j.getRendimiento();
                        jugadores++;
                    }    
                }
                rMedio = rMedio / jugadores;
                rMedioGk = rMedioDf;
                rMedioDf = rMedioDm;
                rMedioDm = rMedioMf;
                rMedioMf = rMedioAm;
                rMedioAm = rMedioFw;
                rMedioFw = rMedio;
                pW.println();
                pW.println("RENDIMIENTO MEDIO: " + df2.format(rMedio) + " puntos");
                pW.println();
                while (media<31){
                    rMedio = 0;
                    jugadores = 0;
                    for (Jugador j: jPosicion){
                        if ((j.getMedias()[0] == media) && (j.getStats().getMinutos()>0)){
                            rMedio += j.getRendimiento();
                            jugadores++;
                        }
                    }
                    if (jugadores != 0) rMedio = rMedio / jugadores;
                    pW.println("RENDIMIENTO MEDIO (MEDIA = " + media + ", " + jugadores + " JUGADORES): " + df2.format(rMedio) + " puntos.");
                    media++;
                }
                pW.println();
                int stat;
                double sMedia;
                String statName = "";
                for (int st = 0; st<7; st++){
                    stat = 0;
                    sMedia = 0;
                    jugadores = 0;
                    for (Jugador j: jPosicion){
                        switch (st){
                            case 0:
                                stat += j.getStats().getParadas();
                                statName = "Sav";
                            break;
                            case 1:
                                stat += j.getStats().getEncajados();
                                statName = "Con";
                            break;
                            case 2:
                                stat += j.getStats().getTackles();
                                statName = "Tk";
                            break;
                            case 3:
                                stat += j.getStats().getPases();
                                statName = "Ps";
                            break;
                            case 4:
                                stat += j.getStats().getTiros();
                                statName = "Sh";
                            break;
                            case 5:
                                stat += j.getStats().getGoles();
                                statName = "Goal";
                            break;
                            case 6:
                                stat += j.getStats().getAsistencias();
                                statName = "Assists";
                            break;
                        }
                        jugadores++;
                    }
                    sMedia = (double)stat / (double)jugadores;
                    pW.println("Numero total de " + statName + ": " + stat + ". Media: " + df2.format(sMedia));
                }
                pW.close();
            }
        } catch (IOException ex) {
            System.out.println ("Error");
        }
    }//GEN-LAST:event_jRendimientoActionPerformed

    private void jSimAutomaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSimAutomaticoActionPerformed
        try {
            liga.cargarCalendarios();
            new SimulacionAuto (this, true, liga).setVisible(true);
        } catch (IOException ex) {
            System.out.println("Error");
        }
    }//GEN-LAST:event_jSimAutomaticoActionPerformed

    private void jSalariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalariosActionPerformed
        Collections.sort(liga.getJugadores(), new CompareJugadoresSalario());
        int [] difTxt = {100, 50, 30, 20};
        for (Equipo e: liga.getEquipos()){
            e.calcularSalario();
        }
        Collections.sort(liga.getEquipos(), new CompareEquiposSalario());
        try {
            File directorio = new File ("Salarios");
            directorio.mkdir();
            DecimalFormat df = new DecimalFormat ("###,###.##");
            BufferedWriter bW;
            PrintWriter pW;
            FileOutputStream jugadores = new FileOutputStream ("\\" + directorio + "\\Salarios Jugadores.txt");
            bW = new BufferedWriter (new OutputStreamWriter(jugadores, "utf-16"));
            pW = new PrintWriter (bW);
            pW.println("NUM    JUGADOR          EQUIPO   SALARIO");
            pW.println("-----------------------------------------------------------");
            int k = 1;
            for (Jugador j: liga.getJugadores()){
                String escribir = "";
                escribir = k + "";
                int espacios = 3;
                for (int i = k; i>=10; i = i/10){
                    espacios = espacios - 1;
                }
                for (int i = 0; i<espacios; i++){
                    escribir += " ";
                }
                escribir += "   ";
                escribir += j.getNombre();
                for (int i = 0; i<14-j.getNombre().length(); i++){
                    escribir += " ";
                }
                escribir += "   ";
                escribir += "(" + j.getEquipo().toLowerCase() + ")    " + df.format(j.getSalario()) + "\u20ac";
                pW.println(escribir);
                k++;
            }
            pW.close();
            for (int porcentaje: difTxt){
                FileOutputStream equipos = new FileOutputStream ("\\" + directorio + "\\Salarios Equipos " + porcentaje + ".txt");
                bW = new BufferedWriter (new OutputStreamWriter(equipos, "utf-16"));
                pW = new PrintWriter (bW);
                pW.println("NUM   EQUIPO  SALARIO");
                pW.println("-----------------------------");
                k=1;
                for (Equipo e: liga.getEquipos()){
                    if (!e.getAbrev().equals("LIB")){
                        String escribir = "";
                        escribir = k + "";
                        int espacios = 1;
                        for (int i = k; i>=10; i = i/10){
                            espacios = espacios - 1;
                        }
                        for (int i = 0; i<espacios; i++){
                            escribir += " ";
                        }
                        escribir += "   ";
                        escribir += "(" + e.getAbrev().toLowerCase() + ")    " + df.format((int)(e.getSalario()*(porcentaje/(double)100))) + "\u20ac";
                        pW.println(escribir);
                        k++;
                    }
                }
                pW.close();
           }
        } catch (IOException ex) {
            System.out.println("Error");
        }
    }//GEN-LAST:event_jSalariosActionPerformed

    private void jEloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEloActionPerformed
        double constante = 50;
        for (Resultado r: liga.getResultados()){
            double puntEsperadaLocal = 1/(1 + Math.pow(10, (((r.getVisitante().getElo() - r.getLocal().getElo())/400))));
            double puntEsperadaVisitante = 1/(1 + Math.pow(10, (((r.getLocal().getElo() - r.getVisitante().getElo())/400))));
            double resLocal, resVisitante;
            if (r.getResLocal()-r.getResVisitante()>0){
                resLocal = 1;
                resVisitante = 0;
            }else if (r.getResLocal()-r.getResVisitante()<0){
                resLocal = 0;
                resVisitante = 1;
            }else{
                resLocal = resVisitante = 0.5;
            }
            r.getLocal().setElo(r.getLocal().getElo() + constante*(resLocal - puntEsperadaLocal));
            r.getVisitante().setElo(r.getVisitante().getElo() + constante*(resVisitante - puntEsperadaVisitante));
        }
        try {
            FileWriter eloEquipos = new FileWriter ("\\" + "ELO Equipos.txt");
            BufferedWriter bW = new BufferedWriter (eloEquipos);
            PrintWriter pW = new PrintWriter (bW);
            pW.println("ELO EQUIPOS ESO");
            pW.println("------------------");
            Collections.sort(liga.getEquipos(), new CompareEquiposELO());
            int i = 1;
            for (Equipo e: liga.getEquipos()){
                if (!e.getAbrev().toLowerCase().equals("lib")){
                    pW.println(i + ". (" + e.getAbrev().toLowerCase() + ") " + Math.round(e.getElo()));
                    i++;
                }
            }
            pW.close();
        } catch (IOException ex) {
            System.out.println("Error");
        }
    }//GEN-LAST:event_jEloActionPerformed

    private void jClasificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClasificacionActionPerformed
        liga.generarClasificacion();
        File clasificacion = new File ("Clasificaciones");
        clasificacion.mkdir();
        LocalDate fecha = LocalDate.now();
        Collections.sort(liga.getClasificaciones().get(0).getEquipos(), new CompareEquipoClas());
        try {
            FileWriter escribirClas = new FileWriter ("\\" + clasificacion + "\\Clasificacion " + fecha.getDayOfMonth() + "-" + fecha.getMonthValue() + "-" + fecha.getYear() + ".txt");
            BufferedWriter bW = new BufferedWriter (escribirClas);
            PrintWriter pW = new PrintWriter (bW);
            pW.println("EQUIPO                       PJ    PG    PE    PP    GF    GC    DG    PTS");
            pW.println("-------------------------------------------------------------");
            int i = 1;
            for (EquipoClas e: liga.getClasificaciones().get(0).getEquipos()){
                pW.println(i + ". " + e);
                i++;
            }
            pW.close();
        } catch (IOException ex) {
            System.out.println("Error");
        }
    }//GEN-LAST:event_jClasificacionActionPerformed

    private void jMensajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMensajesActionPerformed
      new MensajesAutomaticos(this, true, liga).setVisible(true);
    }//GEN-LAST:event_jMensajesActionPerformed

    private void jNumJugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNumJugadoresActionPerformed
        File nJugadores = new File ("Numero de Jugadores");
        nJugadores.mkdir();
        try {
            FileWriter fW = new FileWriter ("\\" + nJugadores + "\\nJugadores.txt");
            BufferedWriter bW = new BufferedWriter (fW);
            PrintWriter pW = new PrintWriter (bW);
            int i = 1;
            Collections.sort (liga.getEquipos(), new CompareEquiposNumJ());
            for (Equipo e: liga.getEquipos()){
                pW.println(i + ". (" + e.getAbrev().toLowerCase() + ") " + e.getRoster().size() + " jugadores.");
                i++;
            }
            pW.close();
        } catch (IOException ex) {
            System.out.println("Error");
        }
        
    }//GEN-LAST:event_jNumJugadoresActionPerformed

    private void jTodosJugadoresPosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTodosJugadoresPosActionPerformed
        String [] archivos = {"GK", "DF", "DM", "MF", "AM", "FW"};
        File carpeta = new File ("Todos los jugadores");
        carpeta.mkdir();
        int i = 1;
        for (String s: archivos){
            try {
                FileWriter fW = new FileWriter ("\\" + carpeta + "\\Todos los " + s + ".txt");
                BufferedWriter bW = new BufferedWriter (fW);
                PrintWriter pW = new PrintWriter (bW);
                liga.escribirCabecera(pW);
                ArrayList<Jugador> jPosicion = new ArrayList();
                for (Jugador j: liga.getJugadores()){
                    if (j.getPosInt() == i)
                        jPosicion.add(new Jugador(j));
                }
                for (Jugador j: jPosicion){
                    j.calcularRendimiento();
                }
                Collections.sort(jPosicion, new CompareJugadoresRend());
                for (Jugador j: jPosicion){
                    pW.println(j.toString() + " (" + j.getEquipo().toLowerCase() + ")");
                }
                pW.close();
                i++;
            } catch (IOException ex) {
                System.out.println("Error");
            }
        }
    }//GEN-LAST:event_jTodosJugadoresPosActionPerformed

    private void jPruebaBonusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPruebaBonusActionPerformed
       File pruebaBonus = new File ("Test Bonus Minutos");
       pruebaBonus.mkdir();
        try {
            FileWriter subidasYBajadas = new FileWriter ("\\" + pruebaBonus + "\\Test bonus de minutos.txt");
            BufferedWriter bW = new BufferedWriter (subidasYBajadas);
            PrintWriter pW = new PrintWriter (bW);
            liga.escribirCabecera(pW);
            for (Jugador j: liga.getJugadores()){
                switch (j.getPosInt()){
                    case 1: j.calcularExpTest(rMedioGk);
                    break;
                    case 2: j.calcularExpTest(rMedioDf);
                    break;
                    case 3: j.calcularExpTest(rMedioDm);
                    break;
                    case 4: j.calcularExpTest(rMedioMf);
                    break;
                    case 5: j.calcularExpTest(rMedioAm);
                    break;
                    case 6: j.calcularExpTest(rMedioFw);
                    break;
                }
            }
            Collections.sort(liga.getJugadores(), new CompareJugadoresTest());
            for (Jugador j: liga.getJugadores()){
                pW.println(j + "        " + j.getExp() + " puntos");
            }
            pW.close();
        } catch (IOException ex) {
            System.out.println("Error");
        }
    }//GEN-LAST:event_jPruebaBonusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jButton1;
        private javax.swing.JButton jButton2;
        private javax.swing.JButton jButton3;
        private javax.swing.JButton jButtonBonusDeMinutos;
        private javax.swing.JButton jButtonCargarPlantillas;
        private javax.swing.JButton jButtonEstadisticas;
        private javax.swing.JButton jButtonMostrarPlantillas;
        private javax.swing.JButton jButtonSelecciones;
        private javax.swing.JButton jButtonTraspasarJugadores;
        private javax.swing.JButton jCargarSelecciones;
        private javax.swing.JButton jClasificacion;
        private javax.swing.JButton jElo;
        private javax.swing.JButton jEntrenamientos;
        private javax.swing.JButton jGuardarJugadoresAZ;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabelFondo;
        private javax.swing.JLabel jLabelIcono;
        private javax.swing.JLabel jLabelParcelaDeportiva;
        private javax.swing.JButton jMensajes;
        private javax.swing.JButton jNumJugadores;
        private javax.swing.JButton jPotenciales;
        private javax.swing.JButton jPruebaBonus;
        private javax.swing.JButton jRendimiento;
        private javax.swing.JButton jSalarios;
        private javax.swing.JButton jSimAutomatico;
        private javax.swing.JButton jSumarFit;
        private javax.swing.JButton jTodosJugadoresEdad;
        private javax.swing.JButton jTodosJugadoresPos;
        // End of variables declaration//GEN-END:variables
}
