/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazGrafica;
import Contenedor.Contenedor;
import EquipoDep.*;
import java.io.*;
import java.util.*;
import java.util.logging.*;
/**
 *
 * @author Antonio
 */
public class jEntrenamientos extends javax.swing.JDialog {
    Contenedor ligaAux;
    int St, Tk, Ps, Sh;
    Equipo resultado;
    /**
     * Creates new form jEntrenamientos
     */
    public jEntrenamientos(java.awt.Frame parent, boolean modal, Contenedor liga) {
        super(parent, modal);
        initComponents();
        ligaAux = liga;
        for (Equipo e: ligaAux.getEquipos()){
            jElegirPlantilla.addItem(e.getAbrev());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSumarExp = new javax.swing.JButton();
        jElegirPlantilla = new javax.swing.JComboBox<>();
        jSemanas = new javax.swing.JComboBox<>();
        jPlantillaElegida = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jExpFW = new javax.swing.JTextField();
        jExpMF = new javax.swing.JTextField();
        jExpDF = new javax.swing.JTextField();
        jExpGK = new javax.swing.JTextField();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSumarExp.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jSumarExp.setText("Sumar Entrenamientos");
        jSumarExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSumarExpActionPerformed(evt);
            }
        });
        getContentPane().add(jSumarExp, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, -1, -1));

        jElegirPlantilla.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jElegirPlantillaItemStateChanged(evt);
            }
        });
        jElegirPlantilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jElegirPlantillaActionPerformed(evt);
            }
        });
        getContentPane().add(jElegirPlantilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 150, -1));

        jSemanas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7" }));
        getContentPane().add(jSemanas, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, -1, -1));

        jPlantillaElegida.setForeground(new java.awt.Color(255, 255, 255));
        jPlantillaElegida.setText("jLabel4");
        getContentPane().add(jPlantillaElegida, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Semanas:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Plantilla");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Jugadores de Campo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Porteros");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jExpFW.setText("SH");
        getContentPane().add(jExpFW, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 60, -1));

        jExpMF.setText("PS");
        getContentPane().add(jExpMF, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 60, -1));

        jExpDF.setText("TK");
        getContentPane().add(jExpDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 60, -1));

        jExpGK.setText("ST");
        getContentPane().add(jExpGK, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 60, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dsfsdfds_2.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, 360, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jElegirPlantillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jElegirPlantillaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jElegirPlantillaActionPerformed

    private void jElegirPlantillaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jElegirPlantillaItemStateChanged
       String abreviatura = jElegirPlantilla.getSelectedItem().toString();
       boolean encontrado = false;
       resultado = new Equipo();
       Iterator i = ligaAux.getEquipos().iterator();
       while (i.hasNext() || !encontrado){
           Equipo e = (Equipo) i.next();
           if (e.getAbrev() == abreviatura){
               encontrado = true;
               resultado = e;
           }
        }
       jPlantillaElegida.setText("Plantilla elegida: " + resultado.getAbrev());
    }//GEN-LAST:event_jElegirPlantillaItemStateChanged

    private void jSumarExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSumarExpActionPerformed
        if (jExpGK.getText().equals("ST")){
            St = 0;
        }else{
            St = Integer.parseInt(jExpGK.getText());
        }
        if (jExpDF.getText().equals("TK")){
            Tk = 0;
        }else{
            Tk = Integer.parseInt(jExpDF.getText());
        }
        if (jExpMF.getText().equals("PS")){
            Ps = 0;
        }else{
            Ps = Integer.parseInt(jExpMF.getText());
        }
        if (jExpFW.getText().equals("SH")){
            Sh = 0;
        }else{
            Sh = Integer.parseInt(jExpFW.getText());
        }
        int semanas = Integer.parseInt(jSemanas.getSelectedItem().toString());
        try {
            FileWriter fichero = new FileWriter ("logEntrenamientos.txt", true);
            BufferedWriter bW = new BufferedWriter (fichero);
            PrintWriter pW = new PrintWriter (bW);
            Calendar fecha = GregorianCalendar.getInstance();
            int dia = fecha.get(Calendar.DAY_OF_MONTH);
            int mes = fecha.get(Calendar.MONTH);
            int año = fecha.get(Calendar.YEAR);
            int hora = fecha.get(Calendar.HOUR_OF_DAY);
            int min = fecha.get(Calendar.MINUTE);
            String fechaAct = dia + "/" + mes + "/" + año;
            String horaAct = hora + ":" + min;
            pW.println(fechaAct + " - " + horaAct + " - Equipo: " + resultado.getAbrev());
            pW.println();
            for (Jugador j: resultado.getRoster()){
                Habilidad [] h = {new Habilidad (j.getGkSkills()), new Habilidad (j.getDfSkills()), new Habilidad(j.getMfSkills()), new Habilidad(j.getFwSkills())};
                if (j.getPosicion() == Jugador.Posicion.gk){
                    j.getGkSkills().setExp(j.getGkSkills().getExp() + semanas * St);
                    if (j.getGkSkills().getMedia()<h[0].getMedia()){
                        pW.println(j.getNombre() + " (" + j.getEquipo() + ") ha bajado su media de portero de " + h[0].getMedia() + " a " + j.getGkSkills().getMedia());
                    }else if (j.getGkSkills().getMedia()>h[0].getMedia()){
                        pW.println(j.getNombre() + " (" + j.getEquipo() + ") ha subido su media de portero de " + h[0].getMedia() + " a " + j.getGkSkills().getMedia());
                    }
                }else{
                    j.getDfSkills().setExp(j.getDfSkills().getExp() + semanas * Tk);
                    if (j.getDfSkills().getMedia()<h[1].getMedia()){
                        pW.println(j.getNombre() + " (" + j.getEquipo() + ") ha bajado su media de defensa de " + h[1].getMedia() + " a " + j.getDfSkills().getMedia());
                    }else if (j.getDfSkills().getMedia()>h[1].getMedia()){
                        pW.println(j.getNombre() + " (" + j.getEquipo() + ") ha subido su media de defensa de " + h[1].getMedia() + " a " + j.getDfSkills().getMedia());
                    }
                    j.getMfSkills().setExp(j.getMfSkills().getExp() + semanas * Ps);
                    if (j.getMfSkills().getMedia()<h[2].getMedia()){
                        pW.println(j.getNombre() + " (" + j.getEquipo() + ") ha bajado su media de medio de " + h[2].getMedia() + " a " + j.getMfSkills().getMedia());
                    }else if (j.getMfSkills().getMedia()>h[2].getMedia()){
                        pW.println(j.getNombre() + " (" + j.getEquipo() + ") ha subido su media de medio de " + h[2].getMedia() + " a " + j.getMfSkills().getMedia());
                    }
                    j.getFwSkills().setExp(j.getFwSkills().getExp() + semanas * Sh);
                    if (j.getFwSkills().getMedia()<h[3].getMedia()){
                        pW.println(j.getNombre() + " (" + j.getEquipo() + ") ha bajado su media de delantero de " + h[3].getMedia() + " a " + j.getFwSkills().getMedia());
                    }else if (j.getFwSkills().getMedia()>h[3].getMedia()){
                        pW.println(j.getNombre() + " (" + j.getEquipo() + ") ha subido su media de delantero de " + h[3].getMedia() + " a " + j.getFwSkills().getMedia());
                    }
                }
                j.definirPosicion();
                j.definirPosInt();
                j.definirMedias();
                j.definirSalario();
            }
            pW.println();
            pW.println("---------------------------------------------------------------------------");
            pW.println();
            pW.close();
        } catch (IOException ex) {
            Logger.getLogger(jEntrenamientos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jSumarExpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jEntrenamientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jEntrenamientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jEntrenamientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jEntrenamientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jEntrenamientos dialog = new jEntrenamientos(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jElegirPlantilla;
    private javax.swing.JTextField jExpDF;
    private javax.swing.JTextField jExpFW;
    private javax.swing.JTextField jExpGK;
    private javax.swing.JTextField jExpMF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jPlantillaElegida;
    private javax.swing.JComboBox<String> jSemanas;
    private javax.swing.JButton jSumarExp;
    // End of variables declaration//GEN-END:variables
}
