/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazGrafica;
import Contenedor.Contenedor;
import EquipoDep.*;
import java.io.*;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Antonio
 */
public class Selecciones extends javax.swing.JDialog {
    Contenedor liga;
    /**
     * Creates new form Selecciones
     */
    public Selecciones(java.awt.Frame parent, boolean modal, Contenedor liga) {
        super(parent, modal);
        initComponents();
        this.liga = liga;
        jComboBox1.addItem("Seleccion");
        ArrayList <String> selecciones = new ArrayList();
        for (Seleccion s: this.liga.getSelecciones()){
            selecciones.add(s.getAbrev());
        }
        Collections.sort(selecciones);
        for(String abrevSeleccion : selecciones){
            jComboBox1.addItem(abrevSeleccion);
        }
        jTextPane1.setContentType("text/html");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jActualizarPlantillas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jActualizarPlantillas.setText("Actualizar plantillas");
        jActualizarPlantillas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jActualizarPlantillasActionPerformed(evt);
            }
        });
        getContentPane().add(jActualizarPlantillas, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Selecciones nacionales MEL");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, -1, 20));

        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 150, -1));

        jButton1.setText("Guardar Selecciones");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, -1, -1));

        jScrollPane1.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 860, 350));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dsfsdfds_2.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Collections.sort(liga.getSelecciones());
            liga.escribirSelecciones();
            FileWriter seleccionesDir = new FileWriter ("selecciones.dir");
            BufferedWriter bW = new BufferedWriter (seleccionesDir);
            PrintWriter pw = new PrintWriter (bW);
            for (Seleccion s: liga.getSelecciones()){
                pw.println(s.getAbrev() + ".txt");
            }
            pw.close();
        } catch (IOException ex) {
            Logger.getLogger(Selecciones.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
       if (jComboBox1.getSelectedItem().toString() != "Seleccion"){
           Seleccion s = liga.existeSeleccion(jComboBox1.getSelectedItem().toString());
           s.ordenarRoster();
           jTextPane1.setText("<html><body>" + s.escribirHTML() + "</body></html>");
       } else {jTextPane1.setText("");}
       
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jActualizarPlantillasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jActualizarPlantillasActionPerformed
       for (Seleccion s: liga.getSelecciones()){
           for (Jugador j: s.getJugadores()){
                boolean encontrado = false;
                Iterator it = liga.getJugadores().iterator();
                Jugador j2 = new Jugador();
                while ((it.hasNext()) && (!encontrado)){
                    j2 = (Jugador) it.next();
                    if (j2.equals(j)){
                       encontrado = true;
                    }
               }
                if (encontrado){
                    j.setEquipo(j2.getEquipo());
                    liga.getJugadores().remove(j2);
                    j2 = new Jugador(j);
                    liga.getJugadores().add(j2);
                    Iterator it2 = liga.getEquipos().iterator();
                    Equipo e = new Equipo();
                    encontrado = false;
                    while ((it2.hasNext())&&!encontrado){
                       e = (Equipo) it2.next();
                       if (e.getAbrev().equals(j2.getEquipo())){
                           encontrado = true;
                       }    
                    }
                    if (encontrado){
                        Iterator it3 = e.getRoster().iterator();
                        boolean estaJugador = false;
                        Jugador j3 = new Jugador();
                        while ((it3.hasNext()) && !estaJugador){
                             j3 = (Jugador) it3.next();
                             if (j2.equals(j3)){
                                 estaJugador = true;
                             } 
                        }
                        if (estaJugador){
                            e.getRoster().remove(j3);
                            j3 = new Jugador (j2);
                            e.getRoster().add(j3);
                        }   
                    }
                }     
           }
       }
    }//GEN-LAST:event_jActualizarPlantillasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Selecciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Selecciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Selecciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Selecciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Selecciones dialog = new Selecciones(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jActualizarPlantillas;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
