/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazGrafica;
import Contenedor.Contenedor;
import EquipoDep.*;
import java.io.*;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
/**
 *
 * @author Antonio
 */
public class TraspasarJugadores extends javax.swing.JDialog {
    Contenedor liga;
    File traspasos = new File ("Traspasos");
    /**
     * Creates new form TraspasarJugadores
     */
    public TraspasarJugadores(java.awt.Frame parent, boolean modal, Contenedor liga) {
        super(parent, modal);
        initComponents();
        this.liga = liga;
        jComboBoxEqDestino.setVisible(false);
        jComboBoxJ1.setVisible(false);
        jComboBoxJ2.setVisible(false);
        jComboBoxJ3.setVisible(false);
        jComboBoxJ4.setVisible(false);
        jComboBoxJ5.setVisible(false);
        jComboBoxJ6.setVisible(false);
        jComboBoxJ7.setVisible(false);
        jComboBoxJ8.setVisible(false);
        jComboBoxJ1.addItem("");
        jComboBoxJ2.addItem("");
        jComboBoxJ3.addItem("");
        jComboBoxJ4.addItem("");
        jComboBoxJ5.addItem("");
        jComboBoxJ6.addItem("");
        jComboBoxJ7.addItem("");
        jComboBoxJ8.addItem("");
        jComboBoxEqOrigen.addItem("Origen");
        jComboBoxEqDestino.addItem("Destino");
        jLogTraspasos.setText("TRASPASOS REALIZADOS:\n--------------------------------------------\n");
        for (Equipo e: liga.getEquipos()){
            jComboBoxEqOrigen.addItem(e.getAbrev());
            jComboBoxEqDestino.addItem(e.getAbrev());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxEqOrigen = new javax.swing.JComboBox<>();
        jComboBoxEqDestino = new javax.swing.JComboBox<>();
        jComboBoxJ1 = new javax.swing.JComboBox<>();
        jComboBoxJ2 = new javax.swing.JComboBox<>();
        jComboBoxJ3 = new javax.swing.JComboBox<>();
        jComboBoxJ4 = new javax.swing.JComboBox<>();
        jComboBoxJ5 = new javax.swing.JComboBox<>();
        jComboBoxJ6 = new javax.swing.JComboBox<>();
        jComboBoxJ7 = new javax.swing.JComboBox<>();
        jComboBoxJ8 = new javax.swing.JComboBox<>();
        jTraspasar = new javax.swing.JButton();
        jLimpiarLog = new javax.swing.JButton();
        jGuardarLog = new javax.swing.JButton();
        jCargarLog = new javax.swing.JButton();
        jGuardarPlantillas = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLogTraspasos = new javax.swing.JTextPane();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Traspasar Jugadores");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Gestor de Traspasos MEL");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Equipo Origen");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Equipo Destino");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, -1, -1));

        jComboBoxEqOrigen.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxEqOrigenItemStateChanged(evt);
            }
        });
        jComboBoxEqOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEqOrigenActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxEqOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 130, -1));

        jComboBoxEqDestino.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxEqDestinoItemStateChanged(evt);
            }
        });
        jComboBoxEqDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEqDestinoActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxEqDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 120, -1));

        jComboBoxJ1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxJ1ItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBoxJ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 100, -1));

        jComboBoxJ2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxJ2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxJ2ItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBoxJ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 100, -1));

        jComboBoxJ3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxJ3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxJ3ItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBoxJ3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 100, -1));

        jComboBoxJ4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBoxJ4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 100, -1));

        jComboBoxJ5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxJ5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxJ5ItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBoxJ5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 100, -1));

        jComboBoxJ6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxJ6.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxJ6ItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBoxJ6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 100, -1));

        jComboBoxJ7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxJ7.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxJ7ItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBoxJ7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 100, -1));

        jComboBoxJ8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBoxJ8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 100, -1));

        jTraspasar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTraspasar.setText("Traspasar Jugador");
        jTraspasar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTraspasarActionPerformed(evt);
            }
        });
        getContentPane().add(jTraspasar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, -1, -1));

        jLimpiarLog.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLimpiarLog.setText("Limpiar Historico");
        jLimpiarLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLimpiarLogActionPerformed(evt);
            }
        });
        getContentPane().add(jLimpiarLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, -1));

        jGuardarLog.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jGuardarLog.setText("Guardar Historico");
        jGuardarLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGuardarLogActionPerformed(evt);
            }
        });
        getContentPane().add(jGuardarLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 420, -1, -1));

        jCargarLog.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCargarLog.setText("Cargar Historico");
        jCargarLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCargarLogActionPerformed(evt);
            }
        });
        getContentPane().add(jCargarLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, -1, -1));

        jGuardarPlantillas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jGuardarPlantillas.setText("Guardar planbtillas");
        jGuardarPlantillas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGuardarPlantillasActionPerformed(evt);
            }
        });
        getContentPane().add(jGuardarPlantillas, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, -1, -1));

        jScrollPane1.setViewportView(jLogTraspasos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 610, 90));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dsfsdfds_2.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-200, -320, 900, 780));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxEqDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEqDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEqDestinoActionPerformed

    private void jComboBoxEqOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEqOrigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEqOrigenActionPerformed

    private void jComboBoxEqOrigenItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxEqOrigenItemStateChanged
        if (jComboBoxEqOrigen.getSelectedItem() != "Origen"){
            jComboBoxEqDestino.setVisible(true);
            jComboBoxJ1.setVisible(true);
            jComboBoxEqDestino.removeItem(jComboBoxEqOrigen.getSelectedItem());
            jComboBoxJ1.removeAllItems();
            jComboBoxJ1.addItem("");
            jComboBoxJ2.removeAllItems();
            jComboBoxJ2.addItem("");
            jComboBoxJ3.removeAllItems();
            jComboBoxJ3.addItem("");
            jComboBoxJ4.removeAllItems();
            jComboBoxJ4.addItem("");
            Iterator it = liga.getEquipos().iterator();
            Equipo e = liga.buscarEquipo(jComboBoxEqOrigen.getSelectedItem().toString());
            for (Jugador j: e.getRoster()){
                jComboBoxJ1.addItem(j.getNombre());
                jComboBoxJ2.addItem(j.getNombre());
                jComboBoxJ3.addItem(j.getNombre());
                jComboBoxJ4.addItem(j.getNombre());
            }
         }
        
    }//GEN-LAST:event_jComboBoxEqOrigenItemStateChanged

    private void jComboBoxEqDestinoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxEqDestinoItemStateChanged
       if (jComboBoxEqDestino.getSelectedItem() != "Destino"){
            
            jComboBoxJ5.removeAllItems();
            jComboBoxJ5.addItem("");
            jComboBoxJ6.removeAllItems();
            jComboBoxJ6.addItem("");
            jComboBoxJ7.removeAllItems();
            jComboBoxJ7.addItem("");
            jComboBoxJ8.removeAllItems();
            jComboBoxJ8.addItem("");
            jComboBoxJ5.setVisible(true);
            Iterator it = liga.getEquipos().iterator();
            Equipo e = liga.buscarEquipo(jComboBoxEqDestino.getSelectedItem().toString());
            for (Jugador j: e.getRoster()){
                jComboBoxJ5.addItem(j.getNombre());
                jComboBoxJ6.addItem(j.getNombre());
                jComboBoxJ7.addItem(j.getNombre());
                jComboBoxJ8.addItem(j.getNombre());
            }
         }
    }//GEN-LAST:event_jComboBoxEqDestinoItemStateChanged

    private void jComboBoxJ1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxJ1ItemStateChanged
       
        if (jComboBoxJ1.getSelectedItem() != ""){
           jComboBoxJ2.removeItem(jComboBoxJ1.getSelectedItem());
           jComboBoxJ3.removeItem(jComboBoxJ1.getSelectedItem());
           jComboBoxJ4.removeItem(jComboBoxJ1.getSelectedItem());
           jComboBoxJ2.setVisible(true);
       }
       else{jComboBoxJ2.setVisible(false); jComboBoxJ2.setSelectedIndex(0); 
            jComboBoxJ3.setVisible(false); jComboBoxJ3.setSelectedIndex(0);
            jComboBoxJ4.setVisible(false); jComboBoxJ4.setSelectedIndex(0);}
    }//GEN-LAST:event_jComboBoxJ1ItemStateChanged

    private void jComboBoxJ2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxJ2ItemStateChanged
       if (jComboBoxJ2.getSelectedItem() != ""){
           jComboBoxJ3.removeItem(jComboBoxJ2.getSelectedItem());
           jComboBoxJ4.removeItem(jComboBoxJ2.getSelectedItem());
           jComboBoxJ3.setVisible(true);
       }
       else{jComboBoxJ3.setVisible(false); jComboBoxJ3.setSelectedIndex(0);
            jComboBoxJ4.setVisible(false); jComboBoxJ4.setSelectedIndex(0);}
    }//GEN-LAST:event_jComboBoxJ2ItemStateChanged

    private void jComboBoxJ3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxJ3ItemStateChanged
        if (jComboBoxJ3.getSelectedItem() != ""){
           jComboBoxJ4.removeItem(jComboBoxJ3.getSelectedItem());
           jComboBoxJ4.setVisible(true);
       }
       else{jComboBoxJ4.setVisible(false); jComboBoxJ4.setSelectedIndex(0);}
    }//GEN-LAST:event_jComboBoxJ3ItemStateChanged

    private void jComboBoxJ5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxJ5ItemStateChanged
        if (jComboBoxJ5.getSelectedItem() != ""){
           jComboBoxJ6.removeItem(jComboBoxJ5.getSelectedItem());
           jComboBoxJ7.removeItem(jComboBoxJ5.getSelectedItem());
           jComboBoxJ8.removeItem(jComboBoxJ5.getSelectedItem());
           jComboBoxJ6.setVisible(true);
       }
       else{jComboBoxJ6.setVisible(false); jComboBoxJ6.setSelectedIndex(0); 
            jComboBoxJ7.setVisible(false); jComboBoxJ7.setSelectedIndex(0);
            jComboBoxJ8.setVisible(false); jComboBoxJ8.setSelectedIndex(0);}
    }//GEN-LAST:event_jComboBoxJ5ItemStateChanged

    private void jComboBoxJ6ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxJ6ItemStateChanged
       if (jComboBoxJ6.getSelectedItem() != ""){
           jComboBoxJ7.removeItem(jComboBoxJ6.getSelectedItem());
           jComboBoxJ8.removeItem(jComboBoxJ6.getSelectedItem());
           jComboBoxJ7.setVisible(true);
       }
       else{jComboBoxJ7.setVisible(false); jComboBoxJ7.setSelectedIndex(0);
            jComboBoxJ8.setVisible(false); jComboBoxJ8.setSelectedIndex(0);}
    }//GEN-LAST:event_jComboBoxJ6ItemStateChanged

    private void jComboBoxJ7ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxJ7ItemStateChanged
        if (jComboBoxJ7.getSelectedItem() != ""){
           jComboBoxJ8.removeItem(jComboBoxJ7.getSelectedItem());
           jComboBoxJ8.setVisible(true);
       }
       else{jComboBoxJ8.setVisible(false); jComboBoxJ8.setSelectedIndex(0);}
    }//GEN-LAST:event_jComboBoxJ7ItemStateChanged

    private void jTraspasarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTraspasarActionPerformed
        if ((jComboBoxEqOrigen.getSelectedItem() != "Origen") && (jComboBoxEqDestino.getSelectedItem() != "Destino")){
            ArrayList <JComboBox> contenedorOrigen = new ArrayList();
            ArrayList <JComboBox> contenedorDestino = new ArrayList();
            contenedorOrigen.add(jComboBoxJ1);
            contenedorOrigen.add(jComboBoxJ2);
            contenedorOrigen.add(jComboBoxJ3);
            contenedorOrigen.add(jComboBoxJ4);
            contenedorDestino.add(jComboBoxJ5);
            contenedorDestino.add(jComboBoxJ6);
            contenedorDestino.add(jComboBoxJ7);
            contenedorDestino.add(jComboBoxJ8);
            for (JComboBox selector: contenedorOrigen){
                if (selector.isVisible() && selector.getSelectedItem() != ""){
                    jLogTraspasos.setText(jLogTraspasos.getText() + "\n" + liga.traspasarJugador(jComboBoxEqOrigen.getSelectedItem().toString(), jComboBoxEqDestino.getSelectedItem().toString(), liga.buscarJugador(selector.getSelectedItem().toString())));
                }
            }
            for (JComboBox selector: contenedorDestino){
                if (selector.isVisible() && selector.getSelectedItem() != ""){
                    jLogTraspasos.setText(jLogTraspasos.getText() + "\n" + liga.traspasarJugador(jComboBoxEqDestino.getSelectedItem().toString(), jComboBoxEqOrigen.getSelectedItem().toString(), liga.buscarJugador(selector.getSelectedItem().toString())));
                }
            }
            
        }else{jLogTraspasos.setText("Error en el traspaso, no se especifico equipo de origen y/o equipo de destino");}
        
    }//GEN-LAST:event_jTraspasarActionPerformed

    private void jLimpiarLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLimpiarLogActionPerformed
       jLogTraspasos.setText("TRASPASOS REALIZADOS:\n--------------------------------------------\n");
    }//GEN-LAST:event_jLimpiarLogActionPerformed

    private void jGuardarPlantillasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGuardarPlantillasActionPerformed
        try {
            liga.guardarEquipos();
        } catch (IOException ex) {
            Logger.getLogger(TraspasarJugadores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jGuardarPlantillasActionPerformed

    private void jGuardarLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGuardarLogActionPerformed
       traspasos.mkdir();
        try {
            FileWriter log = new FileWriter (traspasos + "\\logTraspasos.txt", true);
            BufferedWriter bW = new BufferedWriter (log);
            PrintWriter pW = new PrintWriter (bW);
            StringBuilder s = new StringBuilder(jLogTraspasos.getText());
            s.delete(0, s.indexOf("\n"));
            s = new StringBuilder (s.substring(s.indexOf("E")));
            while (s.toString().contains(".")){
                pW.println(s.substring(0, s.indexOf(".") + 1));
                s.delete(0, s.indexOf(".") + 1);
            }
            pW.println();
            pW.close();
        } catch (IOException ex) {
            System.out.println("Error");
        }
    }//GEN-LAST:event_jGuardarLogActionPerformed

    private void jCargarLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCargarLogActionPerformed
       File log = new File (traspasos + "\\logTraspasos.txt");
       if (log.exists()){
           try {
               FileReader lectura = new FileReader (log);
               BufferedReader bR = new BufferedReader (lectura);
               String s, escribir = "";
               while ((s = bR.readLine())!= null){
                   jLogTraspasos.setText(jLogTraspasos.getText() + s + "\n");
               }
               
           } catch (FileNotFoundException ex) {
               System.out.println ("Fichero no encontrado");
           } catch (IOException ex) {
               System.out.println("Error");
           }
       }
    }//GEN-LAST:event_jCargarLogActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TraspasarJugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TraspasarJugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TraspasarJugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TraspasarJugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TraspasarJugadores dialog = new TraspasarJugadores(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jCargarLog;
    private javax.swing.JComboBox<String> jComboBoxEqDestino;
    private javax.swing.JComboBox<String> jComboBoxEqOrigen;
    private javax.swing.JComboBox<String> jComboBoxJ1;
    private javax.swing.JComboBox<String> jComboBoxJ2;
    private javax.swing.JComboBox<String> jComboBoxJ3;
    private javax.swing.JComboBox<String> jComboBoxJ4;
    private javax.swing.JComboBox<String> jComboBoxJ5;
    private javax.swing.JComboBox<String> jComboBoxJ6;
    private javax.swing.JComboBox<String> jComboBoxJ7;
    private javax.swing.JComboBox<String> jComboBoxJ8;
    private javax.swing.JButton jGuardarLog;
    private javax.swing.JButton jGuardarPlantillas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JButton jLimpiarLog;
    private javax.swing.JTextPane jLogTraspasos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jTraspasar;
    // End of variables declaration//GEN-END:variables
}
